// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyApp.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoneyApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922132156_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoneyApp.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("balance");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("CurrencyCode")
                        .HasDatabaseName("ix_accounts_currency_code");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_accounts_family_id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_accounts_owner_user_id");

                    b.ToTable("accounts", null, t =>
                        {
                            t.HasCheckConstraint("ck_accounts_balance_nonneg", "balance >= 0 OR kind = 3");

                            t.HasCheckConstraint("ck_accounts_module_family", "(kind = 2) = (family_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("MoneyApp.Domain.AccountModuleAccess", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer")
                        .HasColumnName("permissions");

                    b.HasKey("AccountId", "UserId")
                        .HasName("pk_module_permissions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_module_permissions_user_id");

                    b.ToTable("module_permissions", (string)null);
                });

            modelBuilder.Entity("MoneyApp.Domain.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("code");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("integer")
                        .HasColumnName("decimal_places");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("symbol");

                    b.HasKey("Code")
                        .HasName("pk_currencies");

                    b.ToTable("currencies", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "BDT",
                            DecimalPlaces = 2,
                            Name = "Bangladeshi Taka",
                            Symbol = "৳"
                        },
                        new
                        {
                            Code = "USD",
                            DecimalPlaces = 2,
                            Name = "US Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Code = "EUR",
                            DecimalPlaces = 2,
                            Name = "Euro",
                            Symbol = "€"
                        },
                        new
                        {
                            Code = "GBP",
                            DecimalPlaces = 2,
                            Name = "Pound Sterling",
                            Symbol = "£"
                        },
                        new
                        {
                            Code = "INR",
                            DecimalPlaces = 2,
                            Name = "Indian Rupee",
                            Symbol = "₹"
                        },
                        new
                        {
                            Code = "JPY",
                            DecimalPlaces = 0,
                            Name = "Japanese Yen",
                            Symbol = "¥"
                        },
                        new
                        {
                            Code = "CNY",
                            DecimalPlaces = 2,
                            Name = "Chinese Yuan",
                            Symbol = "¥"
                        },
                        new
                        {
                            Code = "AUD",
                            DecimalPlaces = 2,
                            Name = "Australian Dollar",
                            Symbol = "A$"
                        },
                        new
                        {
                            Code = "CAD",
                            DecimalPlaces = 2,
                            Name = "Canadian Dollar",
                            Symbol = "C$"
                        },
                        new
                        {
                            Code = "CHF",
                            DecimalPlaces = 2,
                            Name = "Swiss Franc",
                            Symbol = "CHF"
                        },
                        new
                        {
                            Code = "SGD",
                            DecimalPlaces = 2,
                            Name = "Singapore Dollar",
                            Symbol = "S$"
                        },
                        new
                        {
                            Code = "HKD",
                            DecimalPlaces = 2,
                            Name = "Hong Kong Dollar",
                            Symbol = "HK$"
                        },
                        new
                        {
                            Code = "NZD",
                            DecimalPlaces = 2,
                            Name = "New Zealand Dollar",
                            Symbol = "NZ$"
                        },
                        new
                        {
                            Code = "SEK",
                            DecimalPlaces = 2,
                            Name = "Swedish Krona",
                            Symbol = "kr"
                        },
                        new
                        {
                            Code = "NOK",
                            DecimalPlaces = 2,
                            Name = "Norwegian Krone",
                            Symbol = "kr"
                        },
                        new
                        {
                            Code = "DKK",
                            DecimalPlaces = 2,
                            Name = "Danish Krone",
                            Symbol = "kr"
                        },
                        new
                        {
                            Code = "PLN",
                            DecimalPlaces = 2,
                            Name = "Polish Złoty",
                            Symbol = "zł"
                        },
                        new
                        {
                            Code = "CZK",
                            DecimalPlaces = 2,
                            Name = "Czech Koruna",
                            Symbol = "Kč"
                        },
                        new
                        {
                            Code = "HUF",
                            DecimalPlaces = 2,
                            Name = "Hungarian Forint",
                            Symbol = "Ft"
                        },
                        new
                        {
                            Code = "RUB",
                            DecimalPlaces = 2,
                            Name = "Russian Ruble",
                            Symbol = "₽"
                        },
                        new
                        {
                            Code = "TRY",
                            DecimalPlaces = 2,
                            Name = "Turkish Lira",
                            Symbol = "₺"
                        },
                        new
                        {
                            Code = "AED",
                            DecimalPlaces = 2,
                            Name = "UAE Dirham",
                            Symbol = "د.إ"
                        },
                        new
                        {
                            Code = "SAR",
                            DecimalPlaces = 2,
                            Name = "Saudi Riyal",
                            Symbol = "﷼"
                        },
                        new
                        {
                            Code = "QAR",
                            DecimalPlaces = 2,
                            Name = "Qatari Riyal",
                            Symbol = "﷼"
                        },
                        new
                        {
                            Code = "KWD",
                            DecimalPlaces = 3,
                            Name = "Kuwaiti Dinar",
                            Symbol = "د.ك"
                        },
                        new
                        {
                            Code = "MYR",
                            DecimalPlaces = 2,
                            Name = "Malaysian Ringgit",
                            Symbol = "RM"
                        },
                        new
                        {
                            Code = "IDR",
                            DecimalPlaces = 2,
                            Name = "Indonesian Rupiah",
                            Symbol = "Rp"
                        },
                        new
                        {
                            Code = "THB",
                            DecimalPlaces = 2,
                            Name = "Thai Baht",
                            Symbol = "฿"
                        },
                        new
                        {
                            Code = "PHP",
                            DecimalPlaces = 2,
                            Name = "Philippine Peso",
                            Symbol = "₱"
                        },
                        new
                        {
                            Code = "VND",
                            DecimalPlaces = 0,
                            Name = "Vietnamese Dong",
                            Symbol = "₫"
                        },
                        new
                        {
                            Code = "KRW",
                            DecimalPlaces = 0,
                            Name = "South Korean Won",
                            Symbol = "₩"
                        },
                        new
                        {
                            Code = "PKR",
                            DecimalPlaces = 2,
                            Name = "Pakistani Rupee",
                            Symbol = "₨"
                        },
                        new
                        {
                            Code = "LKR",
                            DecimalPlaces = 2,
                            Name = "Sri Lankan Rupee",
                            Symbol = "Rs"
                        },
                        new
                        {
                            Code = "NPR",
                            DecimalPlaces = 2,
                            Name = "Nepalese Rupee",
                            Symbol = "Rs"
                        },
                        new
                        {
                            Code = "BRL",
                            DecimalPlaces = 2,
                            Name = "Brazilian Real",
                            Symbol = "R$"
                        },
                        new
                        {
                            Code = "MXN",
                            DecimalPlaces = 2,
                            Name = "Mexican Peso",
                            Symbol = "$"
                        },
                        new
                        {
                            Code = "ARS",
                            DecimalPlaces = 2,
                            Name = "Argentine Peso",
                            Symbol = "$"
                        },
                        new
                        {
                            Code = "ZAR",
                            DecimalPlaces = 2,
                            Name = "South African Rand",
                            Symbol = "R"
                        },
                        new
                        {
                            Code = "EGP",
                            DecimalPlaces = 2,
                            Name = "Egyptian Pound",
                            Symbol = "E£"
                        },
                        new
                        {
                            Code = "NGN",
                            DecimalPlaces = 2,
                            Name = "Nigerian Naira",
                            Symbol = "₦"
                        },
                        new
                        {
                            Code = "KES",
                            DecimalPlaces = 2,
                            Name = "Kenyan Shilling",
                            Symbol = "KSh"
                        },
                        new
                        {
                            Code = "ILS",
                            DecimalPlaces = 2,
                            Name = "Israeli Shekel",
                            Symbol = "₪"
                        });
                });

            modelBuilder.Entity("MoneyApp.Domain.ExpenseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.HasKey("Id")
                        .HasName("pk_expense_categories");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_expense_categories_owner_user_id");

                    b.ToTable("expense_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Key = "food"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Key = "groceries"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Key = "dining_out"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Key = "transport"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Key = "fuel"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Key = "rent"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Key = "utilities"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Key = "electricity"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Key = "water"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Key = "gas"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Key = "internet"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Key = "mobile"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Key = "healthcare"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Key = "medicine"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Key = "education"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Key = "tuition"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            Key = "clothing"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            Key = "shopping"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            Key = "entertainment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            Key = "travel"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            Key = "gifts"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            Key = "charity"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            Key = "insurance"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            Key = "household"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            Key = "personal_care"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            Key = "fees"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            Key = "taxes"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            Key = "other"
                        });
                });

            modelBuilder.Entity("MoneyApp.Domain.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("public_id");

                    b.HasKey("Id")
                        .HasName("pk_families");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_families_owner_user_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_families_public_id");

                    b.ToTable("families", (string)null);
                });

            modelBuilder.Entity("MoneyApp.Domain.FamilyMember", b =>
                {
                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("FamilyId", "UserId")
                        .HasName("pk_family_members");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_family_members_user_id");

                    b.ToTable("family_members", (string)null);
                });

            modelBuilder.Entity("MoneyApp.Domain.LedgerTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<Guid?>("FromAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_account_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<Guid?>("ToAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_account_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_transactions_category_id");

                    b.HasIndex("FromAccountId", "CreatedAt")
                        .HasDatabaseName("ix_transactions_from_account_id_created_at");

                    b.HasIndex("ToAccountId", "CreatedAt")
                        .HasDatabaseName("ix_transactions_to_account_id_created_at");

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_tx_amount_pos", "amount > 0");
                        });
                });

            modelBuilder.Entity("MoneyApp.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MoneyApp.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MoneyApp.Domain.Account", b =>
                {
                    b.HasOne("MoneyApp.Domain.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_currencies_currency_code");

                    b.HasOne("MoneyApp.Domain.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_accounts_families_family_id");

                    b.HasOne("MoneyApp.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_users_owner_user_id");
                });

            modelBuilder.Entity("MoneyApp.Domain.AccountModuleAccess", b =>
                {
                    b.HasOne("MoneyApp.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_module_permissions_accounts_account_id");

                    b.HasOne("MoneyApp.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_module_permissions_users_user_id");
                });

            modelBuilder.Entity("MoneyApp.Domain.Family", b =>
                {
                    b.HasOne("MoneyApp.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_families_users_owner_user_id");
                });

            modelBuilder.Entity("MoneyApp.Domain.FamilyMember", b =>
                {
                    b.HasOne("MoneyApp.Domain.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_members_families_family_id");

                    b.HasOne("MoneyApp.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_members_users_user_id");
                });

            modelBuilder.Entity("MoneyApp.Domain.LedgerTransaction", b =>
                {
                    b.HasOne("MoneyApp.Domain.ExpenseCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_expense_categories_category_id");

                    b.HasOne("MoneyApp.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("FromAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_accounts_from_account_id");

                    b.HasOne("MoneyApp.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("ToAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_accounts_to_account_id");
                });

            modelBuilder.Entity("MoneyApp.Domain.RefreshToken", b =>
                {
                    b.HasOne("MoneyApp.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
